issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - dupl
        - testpackage
    - path: /
      linters:
        - gci
        - gofumpt
        - exhaustivestruct
        - wrapcheck
        - tagliatelle
        - varnamelen
  enable-all: true
