apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logfowd.fullname" . }}-config
  labels:
    {{- include "logfowd.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "env": "{{ .Values.app.env }}",
      "debug_mode": {{ .Values.app.debug_mode }},
      "storage": {
        "host": "{{ .Values.app.storage.host }}",
        "port": "{{ .Values.app.storage.port }}",
        "index_name": "{{ .Values.app.storage.index_name }}",
        "flush_interval": {{ .Values.app.storage.flush_interval }},
        "workers": {{ .Values.app.storage.workers }},
        "api_prefix": "{{ .Values.app.storage.api_prefix }}",
        "use_auth": {{ .Values.app.storage.use_auth }},
        "username": "{{ .Values.app.storage.username }}",
        "password": "{{ .Values.app.storage.password }}"
      },
      "logs_path": {{ .Values.app.logs_path | toJson }}
    }