name: Lint & test & build

on: push

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Generate
        run: |-
          mkdir ~/go
          export GOPATH=~/go
          go get github.com/mailru/easyjson
          go install github.com/mailru/easyjson/...@latest
          make gen

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.52.2

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Generate
        run: |-
          mkdir ~/go
          export GOPATH=~/go
          go get github.com/mailru/easyjson
          go install github.com/mailru/easyjson/...@latest
          make gen

      - name: Test
        run: ROOT_DIR=${PWD} go test -failfast ./...
        env:
          CFG_PATH: ./conf/config.example.json
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/logfowd:0.0.11
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/logfowd:latest
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/logfowd:latest,mode=max
